import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    default: 'Next.js Learn', // Default title
    template: '%s | Next.js Learn', // Template for dynamic titles

  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
    <body>
        <header>
          <h1>Header</h1>
        </header>
       
        {children}

        <footer>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  )
}
